### ISSUE TITLE
ERR_REQUIRE_ESM with orbit-db-io 1.1.1-bac86ca.0

### ISSUE THREAD

**Issue by cs145442** [orbitdb/orbit-db-io#39]
Hello Collaborators,
I'm experiencing issues with the latest update of orbit-db-io, which is a dependency for orbit-db.

`Error [ERR_REQUIRE_ESM]: require() of ES Module /<project-path>/node_modules/orbit-db-io/index.js from /<project-path>/node_modules/ipfs-log/src/utils/index.js not supported.`

`Instead change the require of /<project-path>/node_modules/orbit-db-io/index.js in /<project-path>/node_modules/ipfs-log/src/utils/index.js to a dynamic import() which is available in all CommonJS modules.`
`    at Object.<anonymous> (/<project-path>/node_modules/ipfs-log/src/utils/index.js:6:12)`
`    at Object.<anonymous> (/<project-path>/node_modules/ipfs-log/src/entry.js:4:27)`
`    at Object.<anonymous> (/<project-path>/node_modules/ipfs-log/src/log.js:5:15)`
`    at Object.<anonymous> (/<project-path>/node_modules/orbit-db-store/src/Store.js:7:13)`
`    at Object.<anonymous> (/<project-path>/node_modules/orbit-db/src/OrbitDB.js:4:15)`
`    at Object.<anonymous> (/<project-path>/<filename>.js:11:17) {
  code: 'ERR_REQUIRE_ESM'`
`}`

`Node.js v18.5.0`

Hope can will be resolved soon. Thanks.

**Comment by AlexMesser** [comment]
Same here and yes, just from a simple `npm install orbit-db`. As a workaround added `"orbit-db-io": "1.0.1"` dependency in my project `package.json`.
